// Generated by https://quicktype.io

export interface PaginatedItemsData {
    PaginatedItems: Items ;
    latestItems: Datum[],
    popularItems: Datum[],
    bestRatingItems: Datum[],
    categories: Category[];
    categoryStatus: string;
}

export interface Items {
    current_page:   number;
    data:           Datum[];
    first_page_url: string;
    from:           number;
    last_page:      number;
    last_page_url:  string;
    links:          Link[];
    next_page_url:  string | null;
    path:           string;
    per_page:       number;
    prev_page_url:  string | null;
    to:             number;
    total:          number;
}

export interface Datum {
    id:          number;
    title:       string;
    category_id: number;
    price:       number;
    count:       number;
    description: string;
    image:       string;
    created_at:  string;
    updated_at:  string;
    category:    Category;
}

export interface Category {
    id:         number;
    title:      string;
    created_at: string;
    updated_at: string;
}

export interface Link {
    url:    null | string;
    label:  string;
    active: boolean;
}


