// Generated by https://quicktype.io

export interface UserTypes {
    user:  User;
    isAuthenticated: boolean;
    registerError: string;
}

export interface User {
    name:       string;
    email:      string;
    phone:      string;
    role:       string;
    avatar:     string;
    updated_at: string;
    created_at: string;
    id:         number;
    token:      string;
}

export interface RegisterFormData{
    name: string;
    email: string;
    role: string;
    password: string;
    password_confirmation: string;
}

export interface LoginFormData{
    email: string;
    role: string;
    password: string;
}

export interface EmailVerificationFormData{
    email: string;
}

export interface ResetPasswordFormData{
    token: string;
    email: string;
    password: string;
    password_confirmation: string;
}

export interface UserAccountOperationData{
    email_verification_token: string;
}

